### ISSUE TITLE
Emails Trigger

### ISSUE THREAD

**Issue by wishnuadi** [mehulkaklotar/woo-custom-emails#10]
I've set-up the email will be triggered when order status is changed.
In Woocommerce, the first status is on-hold when customers submit their shopping/order.
So, my schenario is, when order status is manually changed from on-hold into pending payment, it should trigger the email. but it didn't work. 
please help me.
Thanks.

**Comment by wishnuadi** [comment]
Sorry, i got some mistake.
first default status on woocommerce is from pending payment to on hold.
if we put the trigger based on this change status, it will work.
it won't work if the trigger based on our custom order status.

as we know, the default order status from woocommerce are 
1. pending payment
2. on hold
3. processing
4. completed
5. failed
6. cancelled
7. refunded

Now i create custom order status, let says "payment received'.
and i put the trigger by order status change from "on hold" into "payment received".
why it doesn't work ?
please somebody can help me ?

thanks.

**Comment by PatelUtkarsh** [comment]
Yes it should work, can you debug and check if `woocommerce_order_status_changed` is being fired ?

**Comment by wishnuadi** [comment]
Thanks Utkarsh for your response.
i'm not familiar with this programming. can you give me a little more details for the files that i need to check? and also how to debug it ?

or you have another way that more simpler than debug to make sure that function is being fired or not.

thanks.

**Comment by mehulkaklotar** [comment]
@wishnuadi WooCommerce does not provide the email trigger hooks for custom post statuses. We will add some UI settings to add custom triggers to handle the scenario in any case.

**Comment by mehulkaklotar** [comment]
@wishnuadi @PatelUtkarsh https://github.com/mehulkaklotar/woo-custom-emails/tree/2.0.4
